In [1]:
#25. Linear Algebra [Vector , Scalar, Tensors, Matrix, Gradiant, Eigen Values and Vectors] 
import numpy as n
import tensorflow as t
s=50
print("Scalar : ",s)
m=n.array([[0, 2],[2, 3]])
v=n.array([[0, 2]])
print("\nMatrix:\n",m)
print("\nVector:\n",v)
print("\nTensor:")
fill_2d = t.fill([3, 3],4, '2d')
fill_string = t.fill([2, 2], "str", 'fill_tensor_string')
print("\nNumerics:\n",fill_2d)
print("\nString:\n",fill_string)
g=n.gradient(m)
print("\nGradient:\n",g)
w,v = n.linalg.eig(m)
mat_norm = n.linalg.norm(m)
print("\nEigen values:\n",w)
print("\nEigen vectors:\n",v)
print("\nMatrix norm:", mat_norm)

Scalar :  50

Matrix:
 [[0 2]
 [2 3]]

Vector:
 [[0 2]]

Tensor:

Numerics:
 tf.Tensor(
[[4 4 4]
 [4 4 4]
 [4 4 4]], shape=(3, 3), dtype=int32)

String:
 tf.Tensor(
[[b'str' b'str']
 [b'str' b'str']], shape=(2, 2), dtype=string)

Gradient:
 [array([[2., 1.],
       [2., 1.]]), array([[2., 2.],
       [1., 1.]])]

Eigen values:
 [-1.  4.]

Eigen vectors:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]

Matrix norm: 4.123105625617661
